apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: weather
  description: Weather main website
  annotations:
    prometheus.io/rule: scrape_duration_seconds
    prometheus.io/alert: all
spec:
  type: website
  lifecycle: production
  owner: team-a
  system: artist-engagement-portal
